version: '3.5'

services:
  database:
    container_name: postgres-db
    image: postgres:10.5-alpine
    volumes:
      - ./$POSTGRES_MIGRATION_PATH:/docker-entrypoint-initdb.d
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    networks:
      - data
    depends_on:
      - database

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - $SMTP_PORT:1025
      - $MAILHOG_CLIENT_PORT:8025

networks:
  data:
