version: '3.5'

services:
  database:
    container_name: postgres-db
    image: postgres:10.5-alpine
    volumes:
      - ./$POSTGRES_MIGRATION_PATH:/docker-entrypoint-initdb.d
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    depends_on:
      - mongo
    networks:
      - data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    networks:
      - data
    depends_on:
      - database

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - $SMTP_PORT:1025
      - $MAILHOG_CLIENT_PORT:8025

  minio:
    container_name: minio
    build:
      context: ./src/infrastructure/storage/local/
      dockerfile: Dockerfile
    ports:
      - $STORAGE_PORT:9000
    environment:
      - MINIO_ACCESS_KEY=$S3_ACCESS_KEY
      - MINIO_SECRET_KEY=$S3_SECRET_KEY
    entrypoint: sh
    command: -c 'mkdir -p /export/bucket && /usr/bin/minio server --address :9000 /export'

  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - $MONGO_PORT:27017
    networks:
      - data

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - data

networks:
  data:
