name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test check
        run: |
          npm install
          npm run test:ci
        env:
          POSTGRES_PORT: 5432
          POSTGRES_USER: miczeq
          POSTGRES_PASSWORD: root
          POSTGRES_DB: data
          POSTGRES_HOST: localhost
          ADMINER_PORT: 8080
